import { Food } from "./app/shared/models/Food"
import { Tag } from "./app/shared/models/Tag"



export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Dum briyani',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['hyderabadi'],
    stars: 4.5,
    imageUrl: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_600/jsfblo0hthfqzuztj3up',
    tags: ['Briyanis', 'Non veg', 'Chiken'],
  },
  {
    id:'2',
    name: 'Grilled Chicken [Full]',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east',],
    stars: 4.7,
    imageUrl: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_600/hmsda0k79yney8b18kly',
    tags: ['Chiken'],
  },
  {
    id:'3',
    name: 'Mutton Biryani',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['hyderabadi'],
    stars: 3.5,
    imageUrl: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_600/aauci23wgnkefdyk5h3w',
    tags: ['Briyanis', 'Non veg'],
  },
  {
    id:'4',
    name: 'Chicken Fried Rice',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Chinese'],
    stars: 3.3,
    imageUrl: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/uzyb0fdwxrjhnhrt2obl',
    tags: ['FastFood', 'Chinese','Non veg','Chiken'],
  },
  {
    id:'5',
    name: 'Veg Biryani',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['indian'],
    stars: 3.0,
    imageUrl: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/qliyg3sjozknqisv43bg',
    tags: ['Briyanis', 'Veg'],
  },
  {
    id:'6',
    name: 'Chicken 65',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/tiltaht7zfitlt1vq6sv',
    tags: ['FastFood', 'Chinese', 'Non veg','Chiken'],
  },
  {
    id:'7',
    name: 'Loose Prawns',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/eixddxvsfqvvabjrdnjj',
    tags: ['FastFood', 'Chinese', 'Non veg'],
  },
  {
    id:'8',
    name: 'Chicken Majestic',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/gsfwnt7plgy4tvtkfumm',
    tags: ['FastFood', 'Chinese', 'Non veg','Chiken'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 8 },
  { name: 'Briyanis', count: 3 },
  { name: 'Chinese', count: 4 },
  { name: 'Fast food', count: 4 },
  { name: 'Veg', count: 1 },
  { name: 'Non veg', count: 7 },
  { name: 'Chiken', count: 5 },
]
